### ISSUE TITLE
Room schedule

### ISSUE THREAD

**Issue by rabestro** [rabestro/wandoo-hotel-reservation-system#21]
# See the schedule for each room

- [x] add endpoint /schedule
- [x] configure security (only employees can see the schedule)
- [x] add ScheduleRequest (roomId, startDate, endDate)
- [x] add bean validation
- [x] add ScheduleResponse 
- [x] add service
- [x] add repository queries
- [x] add tests
